# Generated by Django 4.2.3 on 2023-07-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matrimony", "0002_caste_fatherprofile_hobbies_religion_sect_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hobbies",
            options={"verbose_name_plural": "Hobbies"},
        ),
        migrations.AddField(
            model_name="profile",
            name="sect",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to="matrimony.sect",
            ),
        ),
    ]
